# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "" # the subpath of your site, e.g. /blog
# title: "" # the name of your site, e.g. ACME Corp.

title: "Sense of Steve"
footer_text: "All rights reserved &copy; Steven Koontz 2022"

plugins:
  - jekyll-postcss
  - jekyll-octicons